### ISSUE TITLE
Deprecation warning iOS9

### ISSUE THREAD

**Issue by skuske** [theothertomelliott/TEQuickPageViewController#1]
Any fix for the 'appearanceWhenContainedIn' deprecation warning in iOS 9 in

UIPageControl\* pageControlAppearance = [UIPageControl appearanceWhenContainedIn:[TEQuickPageViewController class], nil];

?
Thanks!

**Comment by theothertomelliott** [comment]
Thanks for letting me know, I've added a compile time check for iOS 9 as the minimum version which should get rid of the warning.

**Comment by skuske** [comment]
Thanks, Tom. Great work! :) 

Stefan 

Am 29.11.2015 20:29, schrieb Tom Elliott: 

> Thanks for letting me know, I've added a compile time check for iOS 9 as the minimum version which should get rid of the warning. 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1]
https://github.com/theothertomelliott/TEQuickPageViewController/issues/1#issuecomment-160455136
